set_property MARK_DEBUG true [get_nets {state_c[0]}]
set_property MARK_DEBUG true [get_nets {state_c[1]}]
set_property MARK_DEBUG true [get_nets {state_c[2]}]
set_property MARK_DEBUG true [get_nets {state_n[0]}]
set_property MARK_DEBUG true [get_nets {state_n[1]}]
set_property MARK_DEBUG true [get_nets {state_n[2]}]
set_property MARK_DEBUG true [get_nets busy_i_IBUF]
set_property MARK_DEBUG true [get_nets convst_o_OBUF]
set_property MARK_DEBUG true [get_nets din_IBUF]
set_property MARK_DEBUG true [get_nets fd_o_OBUF]
set_property MARK_DEBUG true [get_nets rst_n_IBUF]
set_property MARK_DEBUG true [get_nets {ch_cnt[0]}]
set_property MARK_DEBUG true [get_nets {ch_cnt[1]}]
set_property MARK_DEBUG true [get_nets {ch_cnt[2]}]
set_property MARK_DEBUG true [get_nets {ch_cnt[3]}]

set_property MARK_DEBUG true [get_nets rd_o_OBUF]

set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {ch1_data_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {bit_cnt[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {bit_cnt[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {bit_cnt[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {bit_cnt[3]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {bit_cnt[4]_i_1_n_0}]

set_property MARK_DEBUG true [get_nets cs_o_OBUF]

set_property MARK_DEBUG true [get_nets clk_20m]


set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {ch2_data_OBUF[6]}]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF]]


set_property MARK_DEBUG true [get_nets clk_wiz_0_inst/clk_out2]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0_inst/inst/clk_in1_clk_wiz_0]]
connect_debug_port u_ila_0/probe12 [get_nets [list clk_wiz_0_inst/clk_out2]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_in1_clk_wiz_0]


set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF]
