set_property PACKAGE_PIN V16 [get_ports din]
set_property IOSTANDARD LVCMOS33 [get_ports din]
set_property PACKAGE_PIN W16 [get_ports fd_i]
set_property IOSTANDARD LVCMOS33 [get_ports fd_i]
set_property PACKAGE_PIN V15 [get_ports busy_i]
set_property IOSTANDARD LVCMOS33 [get_ports busy_i]

set_property PACKAGE_PIN T15 [get_ports convst_o]
set_property IOSTANDARD LVCMOS33 [get_ports convst_o]
set_property PACKAGE_PIN T14 [get_ports rst_o]
set_property IOSTANDARD LVCMOS33 [get_ports rst_o]
set_property PACKAGE_PIN P16 [get_ports cs_o]
set_property IOSTANDARD LVCMOS33 [get_ports cs_o]
set_property PACKAGE_PIN W15 [get_ports rd_o]
set_property IOSTANDARD LVCMOS33 [get_ports rd_o]
set_property PACKAGE_PIN U17 [get_ports fd_o]
set_property IOSTANDARD LVCMOS33 [get_ports fd_o]