set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/state_c[0]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/state_c[1]}]

set_property MARK_DEBUG true [get_nets convst_o_OBUF]


set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[10]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[12]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[14]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[15]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[1]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[6]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[7]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[9]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[13]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[2]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[5]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[11]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[0]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[3]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[4]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch2_data[8]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[0]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[2]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[6]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[4]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[5]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[9]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[15]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[1]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[10]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[11]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[13]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[3]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[7]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[8]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[12]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/ch1_data[14]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[0]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[1]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[2]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[3]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[4]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[5]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[6]}]
set_property MARK_DEBUG true [get_nets {AD7606_BYTE_inst/din[7]}]
set_property MARK_DEBUG true [get_nets AD7606_BYTE_inst/RD_o]
set_property MARK_DEBUG true [get_nets AD7606_BYTE_inst/rst_o]

set_property PACKAGE_PIN J15 [get_ports {ch1_data[0]}]
set_property PACKAGE_PIN K16 [get_ports {ch1_data[2]}]
set_property PACKAGE_PIN J16 [get_ports {ch1_data[1]}]
set_property PACKAGE_PIN G15 [get_ports {ch1_data[11]}]
set_property PACKAGE_PIN H20 [get_ports {ch1_data[15]}]
set_property PACKAGE_PIN M14 [get_ports {ch1_data[4]}]
set_property PACKAGE_PIN G19 [get_ports {ch1_data[14]}]
set_property PACKAGE_PIN G20 [get_ports {ch1_data[13]}]
set_property PACKAGE_PIN H15 [get_ports {ch1_data[12]}]
set_property PACKAGE_PIN K14 [get_ports {ch1_data[10]}]
set_property PACKAGE_PIN J14 [get_ports {ch1_data[9]}]
set_property PACKAGE_PIN N15 [get_ports {ch1_data[8]}]
set_property PACKAGE_PIN N16 [get_ports {ch1_data[7]}]
set_property PACKAGE_PIN L14 [get_ports {ch1_data[6]}]
set_property PACKAGE_PIN L15 [get_ports {ch1_data[5]}]
set_property PACKAGE_PIN M15 [get_ports {ch1_data[3]}]
set_property PACKAGE_PIN L17 [get_ports {ch2_data[10]}]
set_property PACKAGE_PIN L20 [get_ports {ch2_data[14]}]
set_property PACKAGE_PIN L19 [get_ports {ch2_data[15]}]
set_property PACKAGE_PIN K19 [get_ports {ch2_data[13]}]
set_property PACKAGE_PIN J19 [get_ports {ch2_data[12]}]
set_property PACKAGE_PIN J20 [get_ports {ch2_data[0]}]
set_property PACKAGE_PIN L16 [get_ports {ch2_data[11]}]
set_property PACKAGE_PIN F19 [get_ports {ch2_data[4]}]
set_property PACKAGE_PIN G17 [get_ports {ch2_data[2]}]
set_property PACKAGE_PIN F20 [get_ports {ch2_data[3]}]
set_property PACKAGE_PIN K17 [get_ports {ch2_data[9]}]
set_property PACKAGE_PIN K18 [get_ports {ch2_data[8]}]
set_property PACKAGE_PIN H17 [get_ports {ch2_data[7]}]
set_property PACKAGE_PIN G18 [get_ports {ch2_data[1]}]
set_property PACKAGE_PIN J18 [get_ports {ch2_data[6]}]
set_property PACKAGE_PIN H18 [get_ports {ch2_data[5]}]

set_property MARK_DEBUG false [get_nets {AD7606_BYTE_inst/ch_cnt[0]}]
set_property MARK_DEBUG false [get_nets {AD7606_BYTE_inst/ch_cnt[1]}]
set_property MARK_DEBUG false [get_nets {AD7606_BYTE_inst/ch_cnt[2]}]
set_property MARK_DEBUG false [get_nets {AD7606_BYTE_inst/ch_cnt[3]}]
set_property MARK_DEBUG false [get_nets {AD7606_BYTE_inst/ch_cnt[4]}]

set_property MARK_DEBUG false [get_nets fd_i_IBUF]
set_property MARK_DEBUG true [get_nets fd_o_OBUF]
set_property PACKAGE_PIN M18 [get_ports fd_o]

set_property IOSTANDARD LVCMOS18 [get_ports fd_o]


set_property MARK_DEBUG true [get_nets AD7606_BYTE_inst/busy_neg_edge]
set_property MARK_DEBUG true [get_nets AD7606_BYTE_inst/busy_i]







set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {ch5_data_OBUF[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ch5_data[1]}]
set_property PACKAGE_PIN G14 [get_ports {ch5_data[15]}]
set_property PACKAGE_PIN C20 [get_ports {ch5_data[14]}]
set_property PACKAGE_PIN B20 [get_ports {ch5_data[13]}]
set_property PACKAGE_PIN M19 [get_ports {ch5_data[2]}]
set_property PACKAGE_PIN F17 [get_ports {ch5_data[3]}]
set_property PACKAGE_PIN B19 [get_ports {ch5_data[12]}]
set_property PACKAGE_PIN A20 [get_ports {ch5_data[11]}]
set_property PACKAGE_PIN E17 [get_ports {ch5_data[10]}]
set_property PACKAGE_PIN D18 [get_ports {ch5_data[9]}]
set_property PACKAGE_PIN D19 [get_ports {ch5_data[8]}]
set_property PACKAGE_PIN M17 [get_ports {ch5_data[0]}]
set_property PACKAGE_PIN D20 [get_ports {ch5_data[7]}]
set_property PACKAGE_PIN F16 [get_ports {ch5_data[4]}]
set_property PACKAGE_PIN E18 [get_ports {ch5_data[6]}]
set_property PACKAGE_PIN E19 [get_ports {ch5_data[5]}]
set_property PACKAGE_PIN M20 [get_ports {ch5_data[1]}]
connect_debug_port u_ila_0/probe2 [get_nets [list {ch5_data_OBUF[0]} {ch5_data_OBUF[1]} {ch5_data_OBUF[2]} {ch5_data_OBUF[3]} {ch5_data_OBUF[4]} {ch5_data_OBUF[5]} {ch5_data_OBUF[6]} {ch5_data_OBUF[7]} {ch5_data_OBUF[8]} {ch5_data_OBUF[9]} {ch5_data_OBUF[10]} {ch5_data_OBUF[11]} {ch5_data_OBUF[12]} {ch5_data_OBUF[13]} {ch5_data_OBUF[14]} {ch5_data_OBUF[15]}]]


set_property MARK_DEBUG true [get_nets AD7606_ctrl_inst/ad_convsta]
set_property MARK_DEBUG true [get_nets AD7606_ctrl_inst/ad_rd]
set_property MARK_DEBUG true [get_nets AD7606_ctrl_inst/first_data]
set_property MARK_DEBUG true [get_nets AD7606_ctrl_inst/ad_busy]

set_property MARK_DEBUG true [get_nets {state_o_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {state_o_OBUF[7]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {state_o_OBUF[0]} {state_o_OBUF[1]} {state_o_OBUF[2]} {state_o_OBUF[3]} {state_o_OBUF[4]} {state_o_OBUF[5]} {state_o_OBUF[6]} {state_o_OBUF[7]}]]

set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[0]}]
set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[1]}]
set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[2]}]
set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[3]}]
set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[4]}]
set_property MARK_DEBUG true [get_nets {AD7606_ctrl_inst/state_o[5]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {AD7606_ctrl_inst/state_o[0]} {AD7606_ctrl_inst/state_o[1]} {AD7606_ctrl_inst/state_o[2]} {AD7606_ctrl_inst/state_o[3]} {AD7606_ctrl_inst/state_o[4]} {AD7606_ctrl_inst/state_o[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list AD7606_ctrl_inst/ad_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list AD7606_ctrl_inst/ad_convsta]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list AD7606_ctrl_inst/ad_rd]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list AD7606_ctrl_inst/first_data]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
